Repository ElotlMX/Esquite, pull requests merged in 2020-06, with the labels that each got.

#34 Se renombra aplicación de elotl a esquite
  README.md
  docs/source/conf.py
  docs/source/esquite.rst
  docs/source/index.rst
  esquite/__init__.py
  esquite/context_processors.py
  esquite/settings.py
  esquite/urls.py
  esquite/views.py
  esquite/wsgi.py
  manage.py
Labels: good first issue, python

#37 Arreglando bug cuando no existen variantes
  corpus_admin/views.py
  searcher/helpers.py
Labels: bug

#39 fix(bug): Sin campo en respuesta de elasticsearch
  searcher/helpers.py
Labels: bug

#46 Boton de exportar en Backend
  .gitignore
  corpus_admin/helpers.py
  esquite/settings.py
  searcher/helpers.py
  searcher/urls.py
  searcher/views.py
  templates/base.html
  templates/searcher/searcher.html
Labels: enhancement

#49 Arregla exportar corpus desde el Admin
  corpus_admin/views.py
  esquite/settings.py
  esquite/views.py
  searcher/helpers.py
  searcher/views.py
Labels: bug, refactor
